// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeilunYpeVPkTejPYQ0N_fyczoGjdSJ4M',
    appId: '1:807676594059:web:846aaf9d37b4e4bf3a118e',
    messagingSenderId: '807676594059',
    projectId: 'hydro-ab8d3',
    authDomain: 'hydro-ab8d3.firebaseapp.com',
    storageBucket: 'hydro-ab8d3.firebasestorage.app',
    measurementId: 'G-DTLMH9DS5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmrmxCJ07lSqEbu5ZIeZBdoyjFVM1fDNQ',
    appId: '1:807676594059:android:6727b41a0a98b8f23a118e',
    messagingSenderId: '807676594059',
    projectId: 'hydro-ab8d3',
    storageBucket: 'hydro-ab8d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC60aWC1_wK2PvK9fZ1cd7VRLoiNhDKLyQ',
    appId: '1:807676594059:ios:4538a4f430ad1b513a118e',
    messagingSenderId: '807676594059',
    projectId: 'hydro-ab8d3',
    storageBucket: 'hydro-ab8d3.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC60aWC1_wK2PvK9fZ1cd7VRLoiNhDKLyQ',
    appId: '1:807676594059:ios:4538a4f430ad1b513a118e',
    messagingSenderId: '807676594059',
    projectId: 'hydro-ab8d3',
    storageBucket: 'hydro-ab8d3.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeilunYpeVPkTejPYQ0N_fyczoGjdSJ4M',
    appId: '1:807676594059:web:83eb3e473e06b97b3a118e',
    messagingSenderId: '807676594059',
    projectId: 'hydro-ab8d3',
    authDomain: 'hydro-ab8d3.firebaseapp.com',
    storageBucket: 'hydro-ab8d3.firebasestorage.app',
    measurementId: 'G-R3EP4Q813E',
  );
}
