// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2AWMRZFI6osCnPGHFn9NyQ7zr2NS9kYk',
    appId: '1:160730817149:web:4542da068c41392abf0714',
    messagingSenderId: '160730817149',
    projectId: 'hydro-fe128',
    authDomain: 'hydro-fe128.firebaseapp.com',
    storageBucket: 'hydro-fe128.firebasestorage.app',
    measurementId: 'G-L5EQKT7FRR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmFTGhT1iKarnVvUMhCApksDy10l7DHas',
    appId: '1:160730817149:android:2e41c30f92cb9713bf0714',
    messagingSenderId: '160730817149',
    projectId: 'hydro-fe128',
    storageBucket: 'hydro-fe128.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC10Q6OSJkMAAwjJkLqPPJCS7xvoShbQZM',
    appId: '1:160730817149:ios:5a52b842d4639228bf0714',
    messagingSenderId: '160730817149',
    projectId: 'hydro-fe128',
    storageBucket: 'hydro-fe128.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC10Q6OSJkMAAwjJkLqPPJCS7xvoShbQZM',
    appId: '1:160730817149:ios:5a52b842d4639228bf0714',
    messagingSenderId: '160730817149',
    projectId: 'hydro-fe128',
    storageBucket: 'hydro-fe128.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2AWMRZFI6osCnPGHFn9NyQ7zr2NS9kYk',
    appId: '1:160730817149:web:f7d463c226178dd0bf0714',
    messagingSenderId: '160730817149',
    projectId: 'hydro-fe128',
    authDomain: 'hydro-fe128.firebaseapp.com',
    storageBucket: 'hydro-fe128.firebasestorage.app',
    measurementId: 'G-ZLLS7G6HYY',
  );
}
