// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_0UIu-b_l7VCI03_WLkMEFlPOgkDM0Y',
    appId: '1:748227224617:web:2cf03ab847e1482f4ba838',
    messagingSenderId: '748227224617',
    projectId: 'hydro-3bb12',
    authDomain: 'hydro-3bb12.firebaseapp.com',
    storageBucket: 'hydro-3bb12.firebasestorage.app',
    measurementId: 'G-1D8C6VPHSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg9x7LeppFUZhowiNWXLLqPVsdrsjjQmg',
    appId: '1:748227224617:android:623e9cb585a644a24ba838',
    messagingSenderId: '748227224617',
    projectId: 'hydro-3bb12',
    storageBucket: 'hydro-3bb12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7yxomSb4uPIr4NfJ6HfOQDMtpHnmBXcE',
    appId: '1:748227224617:ios:e56613b1d38dbdb14ba838',
    messagingSenderId: '748227224617',
    projectId: 'hydro-3bb12',
    storageBucket: 'hydro-3bb12.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7yxomSb4uPIr4NfJ6HfOQDMtpHnmBXcE',
    appId: '1:748227224617:ios:e56613b1d38dbdb14ba838',
    messagingSenderId: '748227224617',
    projectId: 'hydro-3bb12',
    storageBucket: 'hydro-3bb12.firebasestorage.app',
    iosBundleId: 'com.example.hydrosecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_0UIu-b_l7VCI03_WLkMEFlPOgkDM0Y',
    appId: '1:748227224617:web:bf6e3972f448dafa4ba838',
    messagingSenderId: '748227224617',
    projectId: 'hydro-3bb12',
    authDomain: 'hydro-3bb12.firebaseapp.com',
    storageBucket: 'hydro-3bb12.firebasestorage.app',
    measurementId: 'G-WRE7WV4DKC',
  );

}