name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.1' # replace with your Flutter version

      # 3. Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # 4. Build Flutter web
      - name: Build Flutter Web
        run: flutter build web --release

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HYDRO_FE128 }}"
          channelId: live
          projectId: hydro-fe128
